#!/usr/bin/env node
/* -*- Mode:js */
/* vim: set expandtab ts=4 sw=4: */
/*
 * You may redistribute this program and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
var Cjdns = require('./lib/cjdnsadmin/cjdnsadmin');
var nThen = require('nthen');
var PublicToIP6 = require('./lib/publicToIp6');

var key2Ip = function (fullAddr) {
    var key = fullAddr.replace(/.*\.([^\.]*\.k)/, function (all, one) { return one; });
    return (PublicToIP6.convert(key));
};

var main = function (argv) {

    var target = argv[argv.length -1];

    var cjdns;
    nThen(function (waitFor) {
	var res = key2Ip(target);
        console.log(target + ' has ip address ' + res);

    });
};
